### ISSUE TITLE
Fix/refactor InputSchema

### ISSUE THREAD

**Issue by aidiss** [valdasjurk/Airplane_accidents_analysis#2]
Do not make all fields nullable.
You might want SOME fields to be coerced.

Use Config to do that. 
https://pandera.readthedocs.io/en/stable/dataframe_models.html#config

Make sure tests are updated.

**Comment by valdasjurk** [comment]
Almost all of the columns has NaN values, so I am not sure how to handle them. Also cannot use gt, le functions as I get error because of the nan values. I added config class in the latest general.py commit.
